### ISSUE TITLE
document API using swagger 

### ISSUE THREAD

**Issue by ahmed2929** [Jimlah/hngi7task2Nodejs#15]

**Comment by mustaphamichael** [comment]
What does this issue entail? 
Can you add a description of the required task?

**Comment by ahmed2929** [comment]
using swagger to document the API (what is expected output and expected input etc ...  @mustaphamichael

**Comment by mustaphamichael** [comment]
Is there a correlation with this closed issue (#5)?

**Comment by ahmed2929** [comment]
no, we finished the design now we need to document everything the API does

**Comment by vickywane** [comment]
I would work on this
